project:
  rego-version: 1
rules:
  style:
    prefer-snake-case:
      # one of "error", "warning", "ignore"
      level: ignore
  imports:
    unresolved-reference:
      # one of "error", "warning", "ignore"
      level: error
      # list of paths that should be ignored
      # these may be paths to data, or rules that may
      # not be present at the time of linting
      # using glob syntax
      except-paths:
        - data.objects
        - data.**.*
    prefer-package-imports:
      # one of "error", "warning", "ignore"
      level: ignore